# Generated by Django 5.1 on 2024-08-10 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduatedStudent',
            fields=[
                ('names', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=6)),
                ('course', models.CharField(max_length=200)),
                ('student_number', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('graduation_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('short-answer', 'Short answer'), ('paragraph', 'Paragraph'), ('multiple-choice', 'Multiple choice'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Dropdown')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('names', models.CharField(max_length=100)),
                ('student_number', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('faculty', models.CharField(max_length=6)),
                ('course', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('FDI', 'FDI'), ('FICT', 'FICT'), ('FCTH', 'FCTH'), ('FCMB', 'FCMB')], max_length=6)),
                ('degree_level', models.CharField(choices=[('Bachelor1`s Degree', 'Bachelor1`s Degree'), ('Bachelor of Arts', 'Bachelor of Arts'), ('Associate Degree', 'Associate Degree'), ('TVET', 'TVET')], max_length=100)),
                ('course', models.CharField(choices=[('DEGREE IN SOFTWARE ENGINEERING & MULTIMEDIA', 'DEGREE IN SOFTWARE ENGINEERING & MULTIMEDIA'), ('DEGREE IN BUSINESS INFORMATION TECHNOLOGY', 'DEGREE IN BUSINESS INFORMATION TECHNOLOGY'), ('DEGREE IN INFORMATION TECHNOLOGY', 'DEGREE IN INFORMATION TECHNOLOGY'), ('DEGREE IN FASHION & APPAREL DESIGN', 'DEGREE IN FASHION & APPAREL DESIGN'), ('DEGREE IN CREATIVE ADVERTISING', 'DEGREE IN CREATIVE ADVERTISING'), ('DEGREE IN GRAPHIC DESIGN', 'DEGREE IN GRAPHIC DESIGN'), ('DEGREE IN HOTEL MANAGEMENT', 'DEGREE IN HOTEL MANAGEMENT'), ('DEGREE IN TOURISM MANAGEMENT', 'DEGREE IN TOURISM MANAGEMENT'), ('DEGREE IN INTERNATIONAL TOURISM', 'DEGREE IN INTERNATIONAL TOURISM')], max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('reason', models.CharField(choices=[('Career Advancement', 'Career Advancement'), ('Personal Interest', 'Personal Interest'), ('To acquire new skills', 'To acquire new skills'), ('Others', 'Others')], max_length=100)),
                ('program_satisfaction', models.CharField(choices=[('Very satisfied', 'Very satisfied'), ('Somewhat satisfied', 'Somewhat satisfied'), ('Neutral', 'Neutral'), ('Somewhat dissatisfied', 'Somewhat dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=100)),
                ('faculty_knowledge', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=100)),
                ('curriculum_satisfaction', models.CharField(choices=[('Very satisfied', 'Very satisfied'), ('Somewhat satisfied', 'Somewhat satisfied'), ('Neutral', 'Neutral'), ('Somewhat dissatisfied', 'Somewhat dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=100)),
                ('academic_advisors', models.CharField(choices=[('Very helpful', 'Very helpful'), ('Somewhat helpful', 'Somewhat helpful'), ('Neutral', 'Neutral'), ('Somewhat unhelpful', 'Somewhat unhelpful'), ('Very unhelpful', 'Very unhelpful')], max_length=100)),
                ('campus_facilities_satisfaction', models.CharField(choices=[('Very satisfied', 'Very satisfied'), ('Somewhat satisfied', 'Somewhat satisfied'), ('Neutral', 'Neutral'), ('Somewhat dissatisfied', 'Somewhat dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=100)),
                ('extracurricular', models.CharField(choices=[('Very satisfied', 'Very satisfied'), ('Somewhat satisfied', 'Somewhat satisfied'), ('Neutral', 'Neutral'), ('Somewhat dissatisfied', 'Somewhat dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=100)),
                ('program_support', models.CharField(choices=[('Very well', 'Very well'), ('Somewhat well', 'Somewhat well'), ('Neutral', 'Neutral'), ('Somewhat poorly', 'Somewhat poorly'), ('Very poorly', 'Very poorly')], max_length=100)),
                ('career_goals', models.CharField(choices=[('Very well', 'Very well'), ('Somewhat well', 'Somewhat well'), ('Neutral', 'Neutral'), ('Somewhat poorly', 'Somewhat poorly'), ('Very poorly', 'Very poorly')], max_length=100)),
                ('career_services', models.CharField(choices=[('DEGREE IN SOFTWARE ENGINEERING & MULTIMEDIA', 'DEGREE IN SOFTWARE ENGINEERING & MULTIMEDIA'), ('DEGREE IN BUSINESS INFORMATION TECHNOLOGY', 'DEGREE IN BUSINESS INFORMATION TECHNOLOGY'), ('DEGREE IN INFORMATION TECHNOLOGY', 'DEGREE IN INFORMATION TECHNOLOGY'), ('DEGREE IN FASHION & APPAREL DESIGN', 'DEGREE IN FASHION & APPAREL DESIGN'), ('DEGREE IN CREATIVE ADVERTISING', 'DEGREE IN CREATIVE ADVERTISING'), ('DEGREE IN GRAPHIC DESIGN', 'DEGREE IN GRAPHIC DESIGN'), ('DEGREE IN HOTEL MANAGEMENT', 'DEGREE IN HOTEL MANAGEMENT'), ('DEGREE IN TOURISM MANAGEMENT', 'DEGREE IN TOURISM MANAGEMENT'), ('DEGREE IN INTERNATIONAL TOURISM', 'DEGREE IN INTERNATIONAL TOURISM')], max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateTimeField()),
                ('target_audience', models.CharField(choices=[('students', 'Students'), ('alumni', 'Alumni')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('student_number', models.CharField(max_length=9, unique=True)),
                ('faculty', models.CharField(max_length=6)),
                ('course', models.CharField(max_length=100)),
                ('graduation_year', models.CharField(max_length=4)),
                ('password', models.CharField(max_length=128)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.TextField()),
                ('company_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employer_profile_pictures/')),
                ('cover_picture', models.ImageField(blank=True, null=True, upload_to='employer_cover_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentAnalysis',
            fields=[
                ('student_number', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('faculty', models.CharField(blank=True, max_length=50)),
                ('course', models.CharField(max_length=200)),
                ('graduation_year', models.CharField(max_length=4)),
                ('employment_status', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('contacts', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('workplace_type', models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('job_location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship')], max_length=50)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('deadline', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumni.employer')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=255)),
                ('gpa', models.FloatField()),
                ('previous_internships', models.TextField()),
                ('skills', models.TextField()),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumni.internshipposting')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('workplace_type', models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('job_location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship')], max_length=50)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('deadline', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='Alumni.employer')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(choices=[('unemployed', 'Unemployed'), ('employed', 'Employed'), ('self_employed', 'Self Employed'), ('studying', 'Studying'), ('self_employed_employed', 'Self Employed and Employed'), ('employed_studying', 'Employed and Studying'), ('self_employed_studying', 'Self Employed and Studying')], max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('job_position', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_in_company', models.CharField(blank=True, max_length=100, null=True)),
                ('is_related_to_profession', models.BooleanField(default=False)),
                ('started_length', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contacts', models.CharField(blank=True, max_length=30, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('cover_picture', models.ImageField(blank=True, null=True, upload_to='cover_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Alumni.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Alumni.survey'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
