# Generated by Django 5.0.4 on 2024-06-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='employer',
        ),
    ]
