# Generated by Django 5.0.4 on 2024-06-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0003_jobposting_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('workplace_type', models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('job_location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship')], max_length=50)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
