# Generated by Django 5.0.4 on 2024-06-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0004_internshipposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumni.employer'),
        ),
    ]
