# Generated by Django 5.0.4 on 2024-06-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0005_jobposting_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
