# Generated by Django 5.0.4 on 2024-06-07 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0006_jobposting_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(choices=[('unemployed', 'Unemployed'), ('employed', 'Employed'), ('self_employed', 'Self Employed'), ('studying', 'Studying'), ('self_employed_employed', 'Self Employed and Employed'), ('employed_studying', 'Employed and Studying'), ('self_employed_studying', 'Self Employed and Studying')], max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('job_position', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_in_company', models.CharField(blank=True, max_length=100, null=True)),
                ('is_related_to_profession', models.BooleanField(default=False)),
                ('started_length', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contacts', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
