# Generated by Django 5.0.4 on 2024-06-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0009_professionaldetails_cover_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='employer_cover_pictures/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='employer_profile_pictures/'),
        ),
    ]
