# Generated by Django 5.0.4 on 2024-06-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0010_employer_cover_picture_employer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaldetails',
            name='skills',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
