# Generated by Django 5.0.4 on 2024-06-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0011_professionaldetails_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipposting',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
