# Generated by Django 5.0.4 on 2024-06-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0017_rename_recipient_notification_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
