# Generated by Django 5.0.4 on 2024-06-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0020_remove_student_id_alter_student_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='names',
        ),
    ]
