# Generated by Django 5.0.4 on 2024-06-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0021_rename_name_student_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student_number',
        ),
    ]
