# Generated by Django 5.0.4 on 2024-06-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0023_question_survey_choice_response_question_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='target_audience',
            field=models.CharField(choices=[('alumni', 'Alumni'), ('students', 'Students'), ('both', 'Both')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('radio', 'Radio Buttons'), ('select', 'Dropdown Menu'), ('checkbox', 'Checkboxes')], default='text', max_length=20),
        ),
    ]
