# Generated by Django 5.0.4 on 2024-08-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0025_rename_text_question_question_text_and_more'),
    ]

    operations = [
    ]
